### PR TITLE
challenge/dani-martorell/strict-equality-function

### PR DESCRIPTION
**Pull request by dmartorell**

### CODE REVIEW

**Review by IrenePerezAlonso — DISMISSED** [review]
Funciona perfecto, buenísimo!

**Review by IsabelGomez87 — DISMISSED** [review]

**Review by jasuarez21 — DISMISSED** [review]
good job!

**Review by gaxxrodri — DISMISSED** [review]

**Review by Laura-SM — DISMISSED** [review]
Good job!

**Review by gaxxrodri — APPROVED** [review]
💯

**Review by Laura-SM — APPROVED** [review]
Good job!

**Review by davzlum — APPROVED** [review]

**Review by SantiagoMC52 — APPROVED** [review]
💯

**Pull request merged**
