### PR TITLE
challenge/isabel gomez marialunarillos

### PR DESCRIPTION
**Pull request by IsabelGomez87**

### CODE REVIEW

**Review by jasuarez21 — APPROVED** [review]

**Review by shd8 — DISMISSED** [review]
Good job Isabel, in the future you can use responsive magnitudes, for example, vh, vw, vmin, vmax or others instead of px. ;)

**Review by Laura-SM — DISMISSED** [review]
Good job!

**Review by annasm07 — DISMISSED** [review]
👏🏼👏🏼👏🏼

**Review by gteixi — DISMISSED** [review]
bye bye _DS.STORE!!!! 👌

**Review by gaxxrodri — APPROVED** [review]

**Review by CheCabeza — APPROVED** [review]

**Review by gteixi — APPROVED** [review]

**Review by jasuarez21 — APPROVED** [review]
— Me da un café con leche corto.

— Se me ha roto la máquina, cambio.

**Pull request merged**
